#ifndef BLE_MESH_APP_PROTOCOL_H_
#define BLE_MESH_APP_PROTOCOL_H_

#include <stdint.h>

#include <zephyr/bluetooth/mesh.h>
#include <zephyr/sys/util.h>

#define APP_VENDOR_COMPANY_ID 0xffff
#define APP_VENDOR_MODEL_ID   0x0001
#define APP_PROTOCOL_VERSION  1

#define APP_GROUP_NODE_STATUS       0xc000
#define APP_GROUP_SERVO_CONTROL     0xc001
#define APP_GROUP_GATEWAY_HEARTBEAT 0xc002

#define APP_HEARTBEAT_INTERVAL_MS 5000
#define APP_ONLINE_NOTIFY_RETRY_MS 2000
#define APP_OFFLINE_TIMEOUT_MS    15000
#define APP_MESH_MAX_PAYLOAD      8

enum app_device_type {
	APP_DEVICE_DHT11 = 1,
	APP_DEVICE_BUTTON = 2,
	APP_DEVICE_SERVO = 3,
};

enum app_node_state_flag {
	APP_NODE_STATE_PROVISIONED = BIT(0),
	APP_NODE_STATE_GATEWAY_REACHABLE = BIT(1),
	APP_NODE_STATE_ALERT = BIT(2),
	APP_NODE_STATE_SENSOR_ERROR = BIT(3),
};

enum app_opcode {
	APP_OPCODE_NODE_HEARTBEAT = 0x01,
	APP_OPCODE_DHT_REPORT = 0x02,
	APP_OPCODE_DHT_ALERT = 0x03,
	APP_OPCODE_BUTTON_EVENT = 0x04,
	APP_OPCODE_SERVO_COMMAND = 0x05,
	APP_OPCODE_SERVO_RESULT = 0x06,
	APP_OPCODE_GATEWAY_HEARTBEAT = 0x07,
	APP_OPCODE_SERVO_CALIBRATE_STOP = 0x08,
	APP_OPCODE_NODE_ONLINE = 0x09,
	APP_OPCODE_NODE_ONLINE_ACK = 0x0a,
};

enum app_dht_metric {
	APP_DHT_METRIC_TEMPERATURE = 1,
	APP_DHT_METRIC_HUMIDITY = 2,
};

enum app_alert_state {
	APP_ALERT_ENTERED = 1,
	APP_ALERT_CLEARED = 2,
};

enum app_servo_command {
	APP_SERVO_COMMAND_RUN = 1,
	APP_SERVO_COMMAND_STOP = 2,
};

enum app_servo_direction {
	APP_SERVO_DIRECTION_STOP = 0,
	APP_SERVO_DIRECTION_FORWARD = 1,
	APP_SERVO_DIRECTION_REVERSE = 2,
};

enum app_servo_result {
	APP_SERVO_RESULT_EXECUTED = 1,
	APP_SERVO_RESULT_STOPPED = 2,
	APP_SERVO_RESULT_SAFE_STOPPED = 3,
	APP_SERVO_RESULT_INVALID = 4,
};

#define APP_MESH_OP(code) BT_MESH_MODEL_OP_3(code, APP_VENDOR_COMPANY_ID)

#endif