#ifndef BLE_MESH_APP_PROTOCOL_H_
#define BLE_MESH_APP_PROTOCOL_H_

#include <stdint.h>

#include <zephyr/bluetooth/mesh.h>
#include <zephyr/sys/util.h>

#define APP_VENDOR_COMPANY_ID 0xffff
#define APP_VENDOR_MODEL_ID   0x0001
#define APP_PROTOCOL_VERSION  1

#define APP_GROUP_NODE_STATUS       0xc000
#define APP_GROUP_SERVO_CONTROL     0xc001
#define APP_GROUP_GATEWAY_HEARTBEAT 0xc002

#define APP_SENSOR_REPORT_INTERVAL_MS     5000
#define APP_NODE_HEARTBEAT_INTERVAL_MS    5000
#define APP_GATEWAY_HEARTBEAT_INTERVAL_MS 5000
#define APP_NODE_PERIODIC_STAGGER_MS       250
#define APP_ONLINE_NOTIFY_RETRY_MS         2000
#define APP_NODE_OFFLINE_TIMEOUT_MS       30000
#define APP_GATEWAY_OFFLINE_TIMEOUT_MS    15000
#define APP_SENSOR_REPROBE_INTERVAL_MS     30000
#define APP_SENSOR_FAILURE_LIMIT               3
#define APP_MESH_MAX_PAYLOAD                   8

#define APP_GATEWAY_ID       "GATEWAY_01"
#define APP_FIRMWARE_VERSION "2.0.0"

enum app_device_type {
	APP_DEVICE_DHT11 = 1,
	APP_DEVICE_BUTTON = 2,
	APP_DEVICE_SERVO = 3,
	APP_DEVICE_PH = 4,
	APP_DEVICE_DO = 5,
	APP_DEVICE_ORP = 6,
	APP_DEVICE_GENERAL_RS485 = 7,
};

enum app_sensor_type {
	APP_SENSOR_PH = 1,
	APP_SENSOR_DO = 2,
	APP_SENSOR_ORP = 3,
	APP_SENSOR_WATER_LEVEL = 4,
};

enum app_sensor_status {
	APP_SENSOR_STATUS_ONLINE = 1,
	APP_SENSOR_STATUS_ERROR = 2,
	APP_SENSOR_STATUS_RECOVERED = 3,
};

enum app_sensor_error {
	APP_SENSOR_ERROR_NONE = 0,
	APP_SENSOR_ERROR_MODBUS = 1,
	APP_SENSOR_ERROR_INVALID_DATA = 2,
};

enum app_transmitter_unit {
	APP_TRANSMITTER_UNIT_MPA = 0,
	APP_TRANSMITTER_UNIT_KPA = 1,
	APP_TRANSMITTER_UNIT_PA = 2,
	APP_TRANSMITTER_UNIT_BAR = 3,
	APP_TRANSMITTER_UNIT_MBAR = 4,
	APP_TRANSMITTER_UNIT_KG_CM2 = 5,
	APP_TRANSMITTER_UNIT_PSI = 6,
	APP_TRANSMITTER_UNIT_MH2O = 7,
	APP_TRANSMITTER_UNIT_MMH2O = 8,
};

enum app_node_state_flag {
	APP_NODE_STATE_PROVISIONED = BIT(0),
	APP_NODE_STATE_GATEWAY_REACHABLE = BIT(1),
	APP_NODE_STATE_ALERT = BIT(2),
	APP_NODE_STATE_SENSOR_ERROR = BIT(3),
};

enum app_opcode {
	APP_OPCODE_NODE_HEARTBEAT = 0x01,
	APP_OPCODE_DHT_REPORT = 0x02,
	APP_OPCODE_DHT_ALERT = 0x03,
	APP_OPCODE_BUTTON_EVENT = 0x04,
	APP_OPCODE_SERVO_COMMAND = 0x05,
	APP_OPCODE_SERVO_RESULT = 0x06,
	APP_OPCODE_GATEWAY_HEARTBEAT = 0x07,
	APP_OPCODE_SERVO_CALIBRATE_STOP = 0x08,
	APP_OPCODE_NODE_ONLINE = 0x09,
	APP_OPCODE_NODE_ONLINE_ACK = 0x0a,
	APP_OPCODE_PH_REPORT = 0x0b,
	APP_OPCODE_PH_CALIBRATE = 0x0c,
	APP_OPCODE_PH_CALIBRATION_RESULT = 0x0d,
	APP_OPCODE_DO_REPORT = 0x0e,
	APP_OPCODE_ORP_REPORT = 0x0f,
	APP_OPCODE_SENSOR_STATUS = 0x10,
	APP_OPCODE_WATER_LEVEL_REPORT = 0x11,
};

enum app_dht_metric {
	APP_DHT_METRIC_TEMPERATURE = 1,
	APP_DHT_METRIC_HUMIDITY = 2,
};

enum app_alert_state {
	APP_ALERT_ENTERED = 1,
	APP_ALERT_CLEARED = 2,
};

enum app_servo_command {
	APP_SERVO_COMMAND_RUN = 1,
	APP_SERVO_COMMAND_STOP = 2,
};

enum app_servo_direction {
	APP_SERVO_DIRECTION_STOP = 0,
	APP_SERVO_DIRECTION_FORWARD = 1,
	APP_SERVO_DIRECTION_REVERSE = 2,
};

enum app_servo_result {
	APP_SERVO_RESULT_EXECUTED = 1,
	APP_SERVO_RESULT_STOPPED = 2,
	APP_SERVO_RESULT_SAFE_STOPPED = 3,
	APP_SERVO_RESULT_INVALID = 4,
};

enum app_ph_calibration_point {
	APP_PH_CALIBRATION_PH_4_00 = 1,
	APP_PH_CALIBRATION_PH_6_86 = 2,
	APP_PH_CALIBRATION_PH_7_00 = 3,
	APP_PH_CALIBRATION_PH_9_18 = 4,
	APP_PH_CALIBRATION_PH_10_00 = 5,
	APP_PH_CALIBRATION_PH_10_01 = 6,
};

enum app_ph_calibration_result {
	APP_PH_CALIBRATION_SUCCESS = 1,
	APP_PH_CALIBRATION_COMMUNICATION_ERROR = 2,
	APP_PH_CALIBRATION_REJECTED = 3,
};

enum app_do_calibration_flag {
	APP_DO_CALIBRATION_AIR_COMPLETE = BIT(0),
	APP_DO_CALIBRATION_ZERO_COMPLETE = BIT(1),
	APP_DO_CALIBRATION_STATUS_KNOWN = BIT(7),
};

#define APP_MESH_OP(code) BT_MESH_MODEL_OP_3(code, APP_VENDOR_COMPANY_ID)

#endif
